_wandb:
    value:
        cli_version: 0.25.1
        e:
            evnqfoju4b1qora8pieox1r7oc90nq0z:
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "13.2"
                disk:
                    /:
                        total: "2000082227200"
                        used: "766451847168"
                email: tcrawley@uwo.ca
                executable: /home/tygo/code/HuMeWoMo/.venv/bin/python
                git:
                    commit: 0b5028a1454e4f140e5e0b60d065940047a99057
                    remote: https://github.com/Dev077/HuMeWoMo.git
                gpu: NVIDIA GeForce RTX 5060 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 4608
                      memoryTotal: "17103323136"
                      name: NVIDIA GeForce RTX 5060 Ti
                      uuid: GPU-df1a0aef-a9da-8d41-9edc-92e026c4ddfd
                host: cachy-ai
                memory:
                    total: "32983281664"
                os: Linux-6.19.7-1-cachyos-x86_64-with-glibc2.43
                program: -m HuMeWoMo.training.train_homo_binding
                python: CPython 3.13.9
                root: /home/tygo/code/HuMeWoMo
                startedAt: "2026-03-22T03:31:14.086046Z"
                writerId: evnqfoju4b1qora8pieox1r7oc90nq0z
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
                - 77
            "2":
                - 1
                - 77
            "3":
                - 16
            "4": 3.13.9
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 4
device:
    value: cuda
drug_in_dim:
    value: 50
enzyme_in_dim:
    value: 27
epochs:
    value: 50
hidden_dim:
    value: 128
learning_rate:
    value: 0.0001
model:
    value: HomoBindingModel
n_heads:
    value: 4
num_decoder_layers:
    value: 3
num_drug_layers:
    value: 3
num_enzyme_layers:
    value: 3
scheduler:
    value: ReduceLROnPlateau
scheduler_factor:
    value: 0.5
scheduler_patience:
    value: 5
weight_decay:
    value: 1e-05
